[package]
name = "persistence"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { workspace = true }
uuid = { workspace = true }
domain = { path = "../domain" }
serde_json = { workspace = true }
